### ISSUE TITLE
1.2.3 zip is corrupt

### ISSUE THREAD

**Issue by JayyKashtaCodes** [Greavesy1899/VisceralToolkit#1]
cant extract it because its a corrupted file

**Comment by Greavesy1899** [comment]
Have you tried using something like 7zip? Otherwise I can try re-zipping to see if it solves the issue

**Comment by JayyKashtaCodes** [comment]
> Have you tried using something like 7zip? Otherwise I can try re-zipping to see if it solves the issue

Yes I have same issue, 7zip refuses to open it.

**Comment by Greavesy1899** [comment]
[Godfather 1.3.zip](https://github.com/Greavesy1899/VisceralToolkit/files/9996093/Godfather.1.3.zip)

Try this please.

**Comment by JayyKashtaCodes** [comment]
> [Godfather 1.3.zip](https://github.com/Greavesy1899/VisceralToolkit/files/9996093/Godfather.1.3.zip)
> 
> Try this please.

Hey sorry its late but that fixed it.
