### ISSUE TITLE
Visceral Tool 1.3 Force Close after running app

### ISSUE THREAD

**Issue by YAGAMI55** [Greavesy1899/VisceralToolkit#2]
Hi. you app closing after double click on it(

Ill read info about format. I can tell you about FFN (inf) font table in DS1-3 Dantes Inferno)

**Comment by Greavesy1899** [comment]
Unfortunately, this is not enough information to diagnose the problem. Can you please tell me the following:
Your OS (and version, eg. Version 10.0.19045 Build 19045)
Hardware, GPU CPU etc

Maybe send some crash dumps too, if any are being created. They can be found in:
C:\Users\USER_NAME\AppData\Local\CrashDumps

**Comment by YAGAMI55** [comment]
OS Win10. CPU Core i5 3470 . 16gb ram. GTX 1050 ti

[VisceralApp.exe.8080.zip](https://github.com/Greavesy1899/VisceralToolkit/files/12313220/VisceralApp.exe.8080.zip)

**Comment by Greavesy1899** [comment]
Can you try v1.4? Not released yet but would be interesting to see if the issue still persists

[VisceralToolkit_v1.4.zip](https://github.com/Greavesy1899/VisceralToolkit/files/12313275/VisceralToolkit_v1.4.zip)

**Comment by YAGAMI55** [comment]
Same issue

**Comment by Greavesy1899** [comment]
Can you try updating your Windows to the latest version of Windows 10? We have recently had issues where the audio system would cause an instant close.

**Comment by Greavesy1899** [comment]
Try this: https://github.com/Greavesy1899/VisceralToolkit/releases/tag/1.4.0
