### ISSUE TITLE
DXGI: no capable adapter found

### ISSUE THREAD

**Issue by Santyspark** [Greavesy1899/VisceralToolkit#3]
hello I tried to run the app and this message appeared, i don´t understand how to manage this since I can run the games and don´t  have any dedicated graphic card, just running on the integrated so, I would like some help please :D

**Comment by Greavesy1899** [comment]
Does the GPU support DX12 or Vulkan? If it doesn't, then this program will not work.

**Comment by Greavesy1899** [comment]
Try this: https://github.com/Greavesy1899/VisceralToolkit/releases/tag/1.4.0
