### ISSUE TITLE
Crashes when I try to export file as rws

### ISSUE THREAD

**Issue by 4rtb** [Greavesy1899/VisceralToolkit#5]

**Comment by Greavesy1899** [comment]
Try this: https://cdn.discordapp.com/attachments/1029317663446540328/1144673296634347550/VisceralToolkit_v1.4.7z?ex=66196494&is=6606ef94&hm=47195c3f91beb81c7460c10c5447122e075b9ca25ba58ac1cde668c9a56201ac&
